language: node_js

env:
    - NODE_ENV=test

node_js:
    - 8

before_install:
    - sudo apt-get update
    - sudo apt-get install -y software-properties-common
    - sudo add-apt-repository -y ppa:nginx/stable
    - sudo apt-get update
    - sudo apt-get install -y --force-yes nginx-extras
    - sudo mkdir -p /tmp/nginx_proxy/cache
    - sudo mkdir -p /var/log/nginx
    - sudo mkdir -p /var/log/nginx

# addons:
#   apt:
#     update: true

script:
    - nginx -c ./nginx.conf
    # - nginx -g 'user www www; daemon off;'

cache:
    yarn: true

notifications:
    email: false